apiVersion: v1
kind: Pod
metadata:
   name: geopm-service-pod
spec:
   restartPolicy: Never
   containers:
   - name: geopm-server
     image: cmcantal/geopm-service:dockerfile
     imagePullPolicy: Always
     securityContext:
       privileged: true
       seccompProfile:
         type: RuntimeDefault
       capabilities:
         drop:
           - all
     command: ['/tmp/geopm-server.sh']
     volumeMounts:
     - name: tmp-mount
       mountPath: /tmp
     - name: geopm-mount
       mountPath: /run/geopm-service
   - name: geopm-client
     image: cmcantal/geopm-service:dockerfile
     imagePullPolicy: Always
     securityContext:
       privileged: false
       allowPrivilegeEscalation: false
       readOnlyRootFilesystem: true
       runAsNonRoot: true
       runAsUser: 10001
       runAsGroup: 10001
     command: ['/tmp/geopm-client.sh']
     volumeMounts:
     - name: tmp-mount
       mountPath: /tmp
     - name: geopm-mount
       mountPath: /run/geopm-service
   volumes:
   - name: tmp-mount
     hostPath:
       path: /tmp
   - name: geopm-mount
     hostPath:
       path: /run/geopm-service
