apiVersion: v1
kind: Pod
metadata:
   name: geopm-service-pod
spec:
   restartPolicy: Never
   containers:
   - name: geopm-server
     image: cmcantal/geopm-service:dockerfile
     imagePullPolicy: Always
     securityContext:
       capabilities:
         add: ["SYS_ADMIN"]
     command: ['/usr/lib/systemd/systemd', '--system', '--unit=geopm']
     volumeMounts:
     - name: host-mount
       mountPath: /tmp
     - name: host-cgroup
       mountPath: /sys/fs/cgroup
     - name: geopm-mount
       mountPath: /run/geopm-service
     - name: dbus-mount
       mountPath: /run/dbus
     - name: systemd-mount
       mountPath: /run/systemd
   - name: geopm-client
     image: cmcantal/geopm-service:dockerfile
     imagePullPolicy: Always
     command: [/tmp/geopm-client.sh]
     volumeMounts:
     - name: host-mount
       mountPath: /tmp
     - name: geopm-mount
       mountPath: /run/geopm-service
     - name: dbus-mount
       mountPath: /run/dbus
     - name: systemd-mount
       mountPath: /run/systemd
   volumes:
   - name: host-mount
     hostPath:
       path: /tmp
   - name: host-cgroup
     hostPath:
       path: /sys/fs/cgroup
   - name: geopm-mount
     hostPath:
       path: /run/geopm-service
   - name: dbus-mount
     hostPath:
       path: /run/dbus
   - name: systemd-mount
     hostPath:
       path: /run/systemd
