apiVersion: v1
kind: Pod
metadata:
   name: open-pbs-execution-pod
spec:
   restartPolicy: Never
   hostname: execution-node-0
   containers:
   - name: open-pbs-execution
     image: cmcantal/open-pbs-execution:dockerfile
     imagePullPolicy: Always
     command: ['/usr/bin/sh', '-c', 'sleep 3600']
