apiVersion: v1
kind: Pod
metadata:
   name: open-pbs-server-pod
spec:
   restartPolicy: Never
   containers:
   - name: open-pbs-server
     image: cmcantal/open-pbs:dockerfile
     imagePullPolicy: Always
     hostname: head-node
     securityContext:
       privileged: true
     command: ['/usr/bin/sh', '-c', 'sed -e "s|PBS_SERVER=.*|PBS_SERVER=head-node|" -e "s|PBS_START_MOM=.*|PBS_START_MOM=1|" -i /etc/pbs.conf; sleep 3600']
