apiVersion: v1
kind: Pod
metadata:
   name: open-pbs-server-pod
   labels:
     name: pbs-server
spec:
   restartPolicy: Never
   hostname: head-node
   subdomain: pbs-server-subdomain
   dnsConfig:
     searches:
       - pbs-server-subdomain.default.svc.cluster.local
   containers:
   - name: pbs-server
     image: cmcantal/open-pbs-server:dockerfile
     imagePullPolicy: Always
     securityContext:
       privileged: true
     command: ['/usr/bin/sh', '-c', 'source /etc/profile.d/pbs.sh; sed -e "s|PBS_SERVER=.*|PBS_SERVER=head-node|" -e "s|PBS_START_MOM=.*|PBS_START_MOM=1|" -i /etc/pbs.conf; useradd bob -m; /etc/init.d/pbs start; sleep 60; qmgr -c "create node execution-node-0"; sleep 3600']
---
apiVersion: v1
kind: Pod
metadata:
   name: open-pbs-execution-pod
   labels:
     name: pbs-server
spec:
   restartPolicy: Never
   hostname: execution-node-0
   subdomain: pbs-server-subdomain
   dnsConfig:
     searches:
       - pbs-server-subdomain.default.svc.cluster.local
   containers:
   - name: pbs-server
     image: cmcantal/open-pbs-execution:dockerfile
     imagePullPolicy: Always
     securityContext:
       privileged: true
     command: ['/usr/bin/sh', '-c', 'sed -e "s|PBS_SERVER=.*|PBS_SERVER=head-node|" -i /etc/pbs.conf; useradd bob -m; /etc/init.d/pbs start; sleep 3600']
---
apiVersion: v1
kind: Service
metadata:
   name: pbs-server-subdomain
spec:
   selector:
     name: pbs-server
   ports:
     - name: pbs-port
       port: 15002
